title: Data Lab
description: |
  Experiment, Analyze, and Discover.
owner: USAspending.gov
first_published: 2018
email: fed-spending-transparency-collaboration@gsa.gov
baseurl: ""
url: https://datalab.usaspending.gov

markdown: kramdown

sass:
  style: compressed