version: '2'
services:
  datalab:
    container_name: datalab
    image: jekyll/jekyll:latest
    restart: always
    working_dir: /datalab-repo-mount
    command: >
        /bin/bash -c "
          bundle install; 
          bundle exec jekyll serve --host=0.0.0.0 --watch --incremental; 
        "
    ports:
        - 4000:4000
    volumes:
        - .:/datalab-repo-mount
