version: '3'
services:
  datalab:
    container_name: datalab
    image: jekyll/jekyll:latest
    restart: always
    command: /bin/bash -c "cd /root/; bundle install; bundle exec jekyll serve --host=0.0.0.0 --watch --incremental"
    ports:
        - 4000:4000
    volumes:
        - .:/root/
